version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/alecthomas/sequel
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            go get -v github.com/jstemmer/go-junit-report
            go get -v -t -d ./...
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s v1.19.1
            mkdir ~/report
          when: always
      - run:
          name: Lint
          command: |
            ./bin/golangci-lint run
      - run:
          name: Test
          command: |
            go test -v ./... 2>&1 | tee report.txt && go-junit-report < report.txt > ~/report/junit.xml
      - store_test_results:
          path: ~/report

